//  Generated by VisionTools - Class Generator v1.0.0
//  2015 Based on Json Class Generator
//  Document Creation Date 2015-07-03

#import <Foundation/Foundation.h>
@protocol CboDataMODEL
@end
@interface CboDataMODEL : NSObject
@property (copy,nonatomic) NSString* value;
@property (copy,nonatomic) NSString* name;
@property (copy,nonatomic) NSString* other;

+ (instancetype)modelWithValue:(NSString *)value name:(NSString *)name;
+ (instancetype)modelWithValue:(NSString *)value name:(NSString *)name other:(NSString *) other;
@end
